#첨부파일
CREATE TABLE ATTACH
(
   ATTF_ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '첨부파일 ID',
   ATTF_ROUTE           VARCHAR(2000) NULL COMMENT '파일경로',
   ATTF_SERNM           VARCHAR(255) NULL COMMENT '서버측파일명',
   ATTF_REALNM          VARCHAR(255) NULL COMMENT '실제파일명',
   ATTF_EXE             VARCHAR(20) NULL COMMENT '파일확장자',
   ATTF_SIZE            BIGINT NULL COMMENT '파일크기'
);


#게시물
CREATE TABLE COMMENT
(
   COMM_ID              BIGINT AUTO_INCREMENT COMMENT '댓글ID',
   POST_ID              BIGINT NOT NULL COMMENT '게시물ID',
   COMM_UPID	        BIGINT NULL COMMENT '상위게시물ID',
   COMM_CONT            VARCHAR(450) NULL COMMENT '내용',
   COMM_WRITER          VARCHAR(18) NULL COMMENT '등록자',
   COMM_DATE            DATETIME NULL COMMENT '등록일시',
   COMM_UWRITER         VARCHAR(18) NULL COMMENT '수정자',
   COMM_UDATE           DATETIME NULL COMMENT '수정일시',
   PRIMARY KEY(COMM_ID, POST_ID)
);


#홈
CREATE TABLE HOME
(
   HOME_ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '집ID',
   USER_ID              BIGINT NOT NULL COMMENT '사용자ID',
   HOME_NAME            VARCHAR(30) NULL COMMENT '집이름',
   HOME_INST            VARCHAR(300) NULL COMMENT '집설명',
   HOME_USE             CHAR(1) NOT NULL COMMENT '활성화여부',
   HOME_THEMA           VARCHAR(36) NULL COMMENT '테마' 
);


#게시물
CREATE TABLE POST
(
   POST_ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '게시물ID',
   POST_CONT            VARCHAR(450) NULL COMMENT '내용',
   POST_WRITER          VARCHAR(18) NULL COMMENT '등록자',
   POST_DATE            DATETIME NOT NULL COMMENT '등록일시',
   POST_UWRITER         VARCHAR(18) NULL COMMENT '수정자',
   POST_UPDATE          DATETIME NOT NULL COMMENT '수정일시',
   HOME_ID            VARCHAR(18) NOT NULL COMMENT '집ID',
   ATTF_ID              BIGINT NULL COMMENT '첨부파일ID'
);



#사용자
CREATE TABLE USER
(
   USER_ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자ID',
   USER_PASS            VARCHAR(300) NULL COMMENT '비밀번호',
   USER_NICK            VARCHAR(18) NULL COMMENT '닉네임',
   USER_JOIN            DATETIME NOT NULL COMMENT '가입일자',
   USER_POWER			VARCHAR(18) NULL COMMENT '관리권한',
   USER_BIRTH           DATE NULL COMMENT '생년월일',
   ATTF_ID              BIGINT NULL COMMENT '첨부파일ID'
);


ALTER TABLE COMMENT
ADD FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID);

ALTER TABLE HOME
ADD FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);

ALTER TABLE USER
ADD FOREIGN KEY (ATTF_ID) REFERENCES ATTACH (ATTF_ID);

ALTER TABLE POST
ADD FOREIGN KEY (ATTF_ID) REFERENCES ATTACH (ATTF_ID);